# Uji Wilcoxon Signed Rank

## Load Library

In [ ]:
from tabulate import tabulate
from scipy.stats import wilcoxon, norm
import pandas as pd

## Define Critical Value from Wilcoxon Table

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
def get_critical_value(n, alpha):
    file_path = "/content/drive/MyDrive/Wilcoxon-Signed-Ranks-Table.xlsx"
    sheet_name = "Signed Rank Table"
    df = pd.read_excel(file_path, sheet_name=sheet_name, usecols="A:H", skiprows=4, nrows=47)
    df.columns = ["n", "alpha_0.2", "alpha_0.1", "alpha_0.05", "alpha_0.02", "alpha_0.01", "alpha_0.002", "alpha_0.001"]
    alpha_col = f"alpha_{alpha}" if f"alpha_{alpha}" in df.columns else None

    if alpha_col is None or n not in df["n"].values:
        return "Gunakan distribusi normal atau tabel Wilcoxon lainnya"

    return df.loc[df["n"] == n, alpha_col].values[0]

## Define Function

### Two-Tail

In [ ]:
def wilcoxon_test(test_type, data1, data2=None, median_assumption=None, alpha=None):

    if test_type == "one_sample":
        print("1. Hipotesis:")
        print(f"H0: Median sampel = {median_assumption}")
        print(f"H1: Median sampel ≠ {median_assumption}")

        differences = [x - median_assumption for x in data1]
        abs_differences = [abs(diff) for diff in differences]

        zero_data = [(x, di, abs_di) for x, di, abs_di in zip(data1, differences, abs_differences) if di == 0]
        nonzero_data = [(x, di, abs_di) for x, di, abs_di in zip(data1, differences, abs_differences) if di != 0]

        sorted_data = sorted(nonzero_data, key=lambda x: x[2])
        ranks = {}

        i = 1
        while i <= len(sorted_data):
            same_values = [sorted_data[i - 1][2]]
            j = i
            while j < len(sorted_data) and sorted_data[j][2] == sorted_data[i - 1][2]:
                same_values.append(sorted_data[j][2])
                j += 1
            avg_rank = sum(range(i, j + 1)) / len(same_values)
            for k in range(i, j + 1):
                ranks[k] = avg_rank
            i = j + 1

        table_data = []
        T_positive = 0
        T_negative = 0
        for i, (x, di, abs_di) in enumerate(sorted_data, start=1):
            rank = ranks[i]
            sign = '+' if di > 0 else '-'
            table_data.append([x, di, abs_di, rank, sign])
            if di > 0:
                T_positive += rank
            else:
                T_negative += rank

        for x, di, abs_di in zero_data:
            table_data.append([x, di, abs_di, '-', '-'])

        headers = ["Data", "di", "|di|", "Rank", "Signed Rank"]
        print(tabulate(table_data, headers=headers, tablefmt="grid"))

        T = min(T_positive, T_negative)
        n = len(sorted_data)

        if n <= 25:
            print("2. Kriteria Uji:")
            print("Jika T < nilai kritis d, maka tolak H0")

            critical_value = get_critical_value(n, alpha)

            print("\n3. Statistika Uji:")
            print(f"Jumlah peringkat positif: {T_positive}")
            print(f"Jumlah peringkat negatif: { T_negative}")
            print(f"Statistik uji Wilcoxon (T): {T}")
            print(f"Alpha: {alpha}")
            print(f"Nilai kritis Wilcoxon (d): {critical_value}")

            print("\n4. Penarikan Kesimpulan")
            if isinstance(critical_value, (int, float)) and T < critical_value:
                print(f"Karena T: {T} < d: {critical_value}")
                print("Kesimpulan: Tolak H0, ada perbedaan yang signifikan.")
            else:
                print(f"Karena T: {T} >= d: {critical_value}")
                print("Kesimpulan: Gagal menolak H0, tidak ada perbedaan yang signifikan.")

        else:
            print("2. Kriteria Uji:")
            print("Jika |Z hitung| > Z tabel, maka tolak H0")

            mu_T = n * (n + 1) / 4
            sigma_T = ((n * (n + 1) * (2 * n + 1)) / 24) ** 0.5
            z = (T - mu_T) / sigma_T
            z_critical = norm.ppf(1 - alpha / 2)

            print("\n3. Statistika Uji:")
            print(f"Jumlah peringkat positif: {T_positive}")
            print(f"Jumlah peringkat negatif: {T_negative}")
            print(f"Statistik uji Wilcoxon (T): {T}")
            print(f"Alpha: {alpha}")

            print(f"Z_hitung: {z}, Z_tabel: ±{z_critical}")

            print("\n4. Penarikan Kesimpulan")
            if abs(z) > z_critical:
                print(f"Karena absolute Z-hitung: {z} > Z-tabel {z_critical}")
                print("Kesimpulan: Tolak H0, ada perbedaan yang signifikan.")
            else:
                print(f"Karena absolute Z-hitung: {z} <= Z-tabel {z_critical}")
                print("Kesimpulan: Gagal menolak H0, tidak ada perbedaan yang signifikan.")

    elif test_type == "paired":
        if len(data1) != len(data2):
            raise ValueError("Panjang data1 dan data2 harus sama")

        print("1. Hipotesis:")
        print("   H0: Tidak ada perbedaan yang signifikan antara kedua sampel")
        print("   H1: Ada perbedaan yang signifikan antara kedua sampel")

        differences = [x - y for x, y in zip(data1, data2)]
        abs_differences = [abs(diff) for diff in differences]

        zero_data = [(d1, d2, di, abs_di) for d1, d2, di, abs_di in zip(data1, data2, differences, abs_differences) if di == 0]
        nonzero_data = [(d1, d2, di, abs_di) for d1, d2, di, abs_di in zip(data1, data2, differences, abs_differences) if di != 0]

        sorted_data = sorted(nonzero_data, key=lambda x: x[3])
        ranks = {}

        i = 1
        while i <= len(sorted_data):
            same_values = [sorted_data[i - 1][3]]
            j = i
            while j < len(sorted_data) and sorted_data[j][3] == sorted_data[i - 1][3]:
                same_values.append(sorted_data[j][3])
                j += 1
            avg_rank = sum(range(i, j + 1)) / len(same_values)
            for k in range(i, j + 1):
                ranks[k] = avg_rank
            i = j + 1

        table_data = []
        T_positive = 0
        T_negative = 0
        for i, (d1, d2, di, abs_di) in enumerate(sorted_data, start=1):
            rank = ranks[i]
            sign = '+' if di > 0 else '-'
            table_data.append([d1, d2, di, abs_di, rank, sign])
            if di > 0:
                T_positive += rank
            else:
                T_negative += rank

        for d1, d2, di, abs_di in zero_data:
            table_data.append([d1, d2, di, abs_di, '-', '-'])

        headers = ["Data1", "Data2", "di", "|di|", "Rank", "Signed Rank"]
        print(tabulate(table_data, headers=headers, tablefmt="grid"))

        T = min(T_positive, T_negative)
        n = len(nonzero_data)

        if n<= 25:
            print("2. Kriteria Uji:")
            print("Jika T < nilai kritis d, maka tolak H0")

            critical_value = get_critical_value(n, alpha)

            print("\n3. Statistika Uji:")
            print(f"Jumlah peringkat positif: {T_positive}")
            print(f"Jumlah peringkat negatif: {T_negative}")
            print(f"Statistik uji Wilcoxon (T): {T}")
            print(f"Alpha: {alpha}")
            print(f"Nilai kritis Wilcoxon (d): {critical_value}")

            print("\n4. Penarikan Kesimpulan")
            if isinstance(critical_value, (int, float)) and T < critical_value:
                print(f"Karena T: {T} < d: {critical_value}")
                print("Kesimpulan: Tolak H0, ada perbedaan yang signifikan.")
            else:
                print(f"Karena T: {T} >= d: {critical_value}")
                print("Kesimpulan: Gagal menolak H0, tidak ada perbedaan yang signifikan.")

        else:
            print("2. Kriteria Uji:")
            print("Jika |Z hitung| > Z tabel, maka tolak H0")

            mu_T = n * (n + 1) / 4
            sigma_T = ((n * (n + 1) * (2 * n + 1)) / 24) ** 0.5
            z = (T - mu_T) / sigma_T
            z_critical = norm.ppf(1 - alpha / 2)

            print("\n3. Statistika Uji:")
            print(f"Jumlah peringkat positif: {T_positive}")
            print(f"Jumlah peringkat negatif: {T_negative}")
            print(f"Statistik uji Wilcoxon (T): {T}")
            print(f"Alpha: {alpha}")

            print(f"Z_hitung: {z}, Z_tabel: ±{z_critical}")

            print("\n4. Penarikan Kesimpulan")
            if abs(z) > z_critical:
                print(f"Karena absolute Z-hitung: {z} > Z-tabel {z_critical}")
                print("Kesimpulan: Tolak H0, ada perbedaan yang signifikan.")
            else:
                print(f"Karena absolute Z-hitung: {z} <= Z-tabel {z_critical}")
                print("Kesimpulan: Gagal menolak H0, tidak ada perbedaan yang signifikan.")


    else:
        print("Jenis uji tidak valid. Gunakan 'one_sample' atau 'paired'.")

# two tail n one tail

In [ ]:
import math
from collections import Counter
import numpy as np

In [ ]:
def wilcoxon_test(test_type, data1, data2=None, median_assumption=None, alpha=None, alternative=None):

    if test_type == "one_sample":

        differences = [x - median_assumption for x in data1]
        abs_differences = [abs(diff) for diff in differences]

        zero_data = [(x, di, abs_di) for x, di, abs_di in zip(data1, differences, abs_differences) if di == 0]
        nonzero_data = [(x, di, abs_di) for x, di, abs_di in zip(data1, differences, abs_differences) if di != 0]

        sorted_data = sorted(nonzero_data, key=lambda x: x[2])
        ranks = {}

        i = 1
        while i <= len(sorted_data):
            same_values = [sorted_data[i - 1][2]]
            j = i
            while j < len(sorted_data) and sorted_data[j][2] == sorted_data[i - 1][2]:
                same_values.append(sorted_data[j][2])
                j += 1
            avg_rank = sum(range(i, j + 1)) / len(same_values)
            for k in range(i, j + 1):
                ranks[k] = avg_rank
            i = j + 1

        table_data = []
        T_positive = 0
        T_negative = 0
        for i, (x, di, abs_di) in enumerate(sorted_data, start=1):
            rank = ranks[i]
            sign = '+' if di > 0 else '-'
            table_data.append([x, di, abs_di, rank, sign])
            if di > 0:
                T_positive += rank
            else:
                T_negative += rank

        for x, di, abs_di in zero_data:
            table_data.append([x, di, abs_di, '-', '-'])

        headers = ["Data", "di", "|di|", "Rank", "Signed Rank"]

        n = len(sorted_data)

        if n <= 25:
            critical_value = get_critical_value(n, alpha)

            if alternative == "two-sided":
                print("1. Hipotesis:")
                print(f"H0: Median sampel = {median_assumption}")
                print(f"H1: Median sampel ≠ {median_assumption}")

                print("2. Kriteria Uji:")
                print("Jika T < nilai kritis d, maka tolak H0")

                print(tabulate(table_data, headers=headers, tablefmt="grid"))

                print("\n3. Statistika Uji:")
                print(f"Jumlah peringkat positif: {T_positive}")
                print(f"Jumlah peringkat negatif: { T_negative}")

                T = min(T_positive, T_negative)

                print(f"Statistik uji Wilcoxon (T): {T}")
                print(f"Alpha: {alpha}")
                print(f"Nilai kritis Wilcoxon (d): {critical_value}")

                print("\n4. Penarikan Kesimpulan")

                if isinstance(critical_value, (int, float)) and T < critical_value:
                    print(f"Karena T: {T} < d: {critical_value}")
                    print("Kesimpulan: Tolak H0, ada perbedaan yang signifikan antara median data dengan median yang disumsikan.")

                else:
                    print(f"Karena T: {T} >= d: {critical_value}")
                    print("Kesimpulan: Gagal menolak H0, tidak ada perbedaan yang signifikan antara median data dengan median yang disumsikan.")

            elif alternative == "greater":
                print("1. Hipotesis:")
                print(f"H0: Median sampel ≤ {median_assumption}")
                print(f"H1: Median sampel > {median_assumption}")

                print(tabulate(table_data, headers=headers, tablefmt="grid"))

                print("2. Kriteria Uji:")
                print("Jika T- < nilai kritis d, maka tolak H0")

                print("\n3. Statistika Uji:")
                print(f"Jumlah peringkat positif: {T_positive}")
                print(f"Jumlah peringkat negatif: { T_negative}")

                print(f"Statistik uji Wilcoxon (T-): {T_negative}")
                print(f"Alpha: {alpha}")
                print(f"Nilai kritis Wilcoxon (d): {critical_value}")

                print("\n4. Penarikan Kesimpulan")

                if isinstance(critical_value, (int, float)) and T_negative < critical_value:
                    print(f"Karena T-: {T_negative} < d: {critical_value}")
                    print("Kesimpulan: Tolak H0, median yang diasumsikan lebih kecil daripada median data.")

                else:
                    print(f"Karena T: {T_negative} >= d: {critical_value}")
                    print("Kesimpulan: Gagal menolak H0, median yang diasumsikan lebih besar atau sama dengan median data.")

            elif alternative == "less":
                print("1. Hipotesis:")
                print(f"H0: Median sampel ≥ {median_assumption}")
                print(f"H1: Median sampel < {median_assumption}")

                print(tabulate(table_data, headers=headers, tablefmt="grid"))

                print("\n3. Statistika Uji:")
                print(f"Jumlah peringkat positif: {T_positive}")
                print(f"Jumlah peringkat negatif: { T_negative}")

                print(f"Statistik uji Wilcoxon (T+): {T_positive}")
                print(f"Alpha: {alpha}")
                print(f"Nilai kritis Wilcoxon (d): {critical_value}")

                print("\n4. Penarikan Kesimpulan")

                if isinstance(critical_value, (int, float)) and T_positive < critical_value:
                    print(f"Karena T+: {T_positive} < d: {critical_value}")
                    print("Kesimpulan: Tolak H0, median yang diasumsikan lebih besar daripada median data.")

                else:
                    print(f"Karena T: {T_positive} >= d: {critical_value}")
                    print("Kesimpulan: Gagal menolak H0, median yang diasumsikan lebih kecil atau sama dengan median data.")

            else:
                print("Pilihan alternative harus 'two-sided', 'greater', atau 'less'.")

        else:
            print("1. Hipotesis:")
            print("H0: Tidak ada perbedaan yang signifikan.")
            print("H1: Ada perbedaan yang signifikan.")

            print(tabulate(table_data, headers=headers, tablefmt="grid"))

            rank_counts = Counter(ranks)
            tied_ranks = [count for count in rank_counts.values() if count > 1]

            mu_T = n * (n + 1) / 4
            sigma_T = ((n * (n + 1) * (2 * n + 1)) / 24) ** 0.5

            if tied_ranks:
                sum_t3 = sum(t**3 for t in tied_ranks)  # Σ t³
                sum_t = sum(tied_ranks)  # Σ t
                correction = (sum_t3 - sum_t) / 48  # Koreksi

                std_T = ((n * (n + 1) * (2 * n + 1)) / 24 - correction) ** 0.5

            print("\n2. Kriteria Uji:")

            if alternative == "two-sided":
                print ("Jika |Z hitung| >= Z tabel, maka tolak H0")
                z_critical = norm.ppf(1 - alpha / 2)
                print(f"Z_tabel: ±{z_critical}")

                z = (min(T_negative, T_positive) - mu_T) / sigma_T

            elif alternative == "greater":
                print("Jika Z hitung > Z tabel, maka tolak H0")
                z_critical = norm.ppf(1 - alpha)
                print(f"Z_tabel: {z_critical}")

                z = (T_negative - mu_T) / sigma_T

            elif alternative == "less":
                print("Jika Z hitung < Z tabel, maka tolak H0")
                z_critical = norm.ppf(alpha)
                print(f"Z_tabel: {z_critical}")

                z = (T_positive - mu_T) / sigma_T

            else:
                print("Pilihan alternative harus 'two-sided', 'greater', atau 'less'.")

            print("\n3. Statistika Uji:")
            print(f"Jumlah peringkat positif: {T_positive}")
            print(f"Jumlah peringkat negatif: {T_negative}")
            # print(f"Statistik uji Wilcoxon (T): {T}")
            print(f"Alpha: {alpha}")

            print(f"Z_hitung: {z}, Z_tabel: ±{z_critical}")

            print("\n4. Penarikan Kesimpulan")

            if (alternative == "two-sided" and abs(z) >= z_critical) or \
               (alternative == "greater" and z > z_critical) or \
               (alternative == "less" and z < z_critical):
               print("Kesimpulan: Tolak H0, ada perbedaan yang signifikan.")

            else:
                print("Kesimpulan: Gagal menolak H0, tidak ada perbedaan yang signifikan.")


    elif test_type == "paired":
        if len(data1) != len(data2):
            raise ValueError("Panjang data1 dan data2 harus sama")

        print("1. Hipotesis:")
        print("H0: Tidak ada perbedaan yang signifikan antara kedua sampel")
        print("H1: Ada perbedaan yang signifikan antara kedua sampel")

        differences = [x - y for x, y in zip(data1, data2)]
        abs_differences = [abs(diff) for diff in differences]

        zero_data = [(d1, d2, di, abs_di) for d1, d2, di, abs_di in zip(data1, data2, differences, abs_differences) if di == 0]
        nonzero_data = [(d1, d2, di, abs_di) for d1, d2, di, abs_di in zip(data1, data2, differences, abs_differences) if di != 0]

        sorted_data = sorted(nonzero_data, key=lambda x: x[3])
        ranks = {}

        i = 1
        while i <= len(sorted_data):
            same_values = [sorted_data[i - 1][3]]
            j = i
            while j < len(sorted_data) and sorted_data[j][3] == sorted_data[i - 1][3]:
                same_values.append(sorted_data[j][3])
                j += 1
            avg_rank = sum(range(i, j + 1)) / len(same_values)
            for k in range(i, j + 1):
                ranks[k] = avg_rank
            i = j + 1

        table_data = []
        T_positive = 0
        T_negative = 0
        for i, (d1, d2, di, abs_di) in enumerate(sorted_data, start=1):
            rank = ranks[i]
            sign = '+' if di > 0 else '-'
            table_data.append([d1, d2, di, abs_di, rank, sign])
            if di > 0:
                T_positive += rank
            else:
                T_negative += rank

        for d1, d2, di, abs_di in zero_data:
            table_data.append([d1, d2, di, abs_di, '-', '-'])

        headers = ["Data1", "Data2", "di", "|di|", "Rank", "Signed Rank"]
        print(tabulate(table_data, headers=headers, tablefmt="grid"))

        T = min(T_positive, T_negative)
        n = len(nonzero_data)

        if n<= 25:
            print("2. Kriteria Uji:")
            print("Jika T < nilai kritis d, maka tolak H0")

            critical_value = get_critical_value(n, alpha)

            print("\n3. Statistika Uji:")
            print(f"Jumlah peringkat positif: {T_positive}")
            print(f"Jumlah peringkat negatif: {T_negative}")
            print(f"Statistik uji Wilcoxon (T): {T}")
            print(f"Alpha: {alpha}")
            print(f"Nilai kritis Wilcoxon (d): {critical_value}")

            print("\n4. Penarikan Kesimpulan")
            if isinstance(critical_value, (int, float)) and T < critical_value:
                print(f"Karena T: {T} < d: {critical_value}")
                print("Kesimpulan: Tolak H0, ada perbedaan yang signifikan.")
            else:
                print(f"Karena T: {T} >= d: {critical_value}")
                print("Kesimpulan: Gagal menolak H0, tidak ada perbedaan yang signifikan.")

        else:
            print("2. Kriteria Uji:")
            print("Jika |Z hitung| > Z tabel, maka tolak H0")

            rank_counts = Counter(ranks)
            tied_ranks = [count for count in rank_counts.values() if count > 1]

            mu_T = n * (n + 1) / 4
            sigma_T = ((n * (n + 1) * (2 * n + 1)) / 24) ** 0.5

            if tied_ranks:
                sum_t3 = sum(t**3 for t in tied_ranks)  # Σ t³
                sum_t = sum(tied_ranks)  # Σ t
                correction = (sum_t3 - sum_t) / 48  # Koreksi

                std_T = ((n * (n + 1) * (2 * n + 1)) / 24 - correction) ** 0.5


            z = (T - mu_T) / sigma_T
            z_critical = norm.ppf(1 - alpha / 2)

            print("\n3. Statistika Uji:")
            print(f"Jumlah peringkat positif: {T_positive}")
            print(f"Jumlah peringkat negatif: {T_negative}")
            print(f"Statistik uji Wilcoxon (T): {T}")
            print(f"Alpha: {alpha}")

            print(f"Z_hitung: {z}, Z_tabel: ±{z_critical}")

            print("\n4. Penarikan Kesimpulan")
            if abs(z) > z_critical:
                print(f"Karena absolute Z-hitung: {z} > Z-tabel {z_critical}")
                print("Kesimpulan: Tolak H0, ada perbedaan yang signifikan.")
            else:
                print(f"Karena absolute Z-hitung: {z} <= Z-tabel {z_critical}")
                print("Kesimpulan: Gagal menolak H0, tidak ada perbedaan yang signifikan.")

    else:
        print("Jenis uji tidak valid. Gunakan 'one_sample' atau 'paired'.")

### Test the Function

In [ ]:
test_type = 'one_sample'
data1 = [99, 100, 90, 94, 135, 108, 107, 111, 119, 104, 127, 109, 117, 105, 125]
median_assumption = 107
alpha = 0.05
wilcoxon_test(test_type, data1, median_assumption=median_assumption, alpha=alpha, alternative='two-sided')

1. Hipotesis:
H0: Median sampel = 107
H1: Median sampel ≠ 107
2. Kriteria Uji:
Jika T < nilai kritis d, maka tolak H0
+--------+------+--------+--------+---------------+
|   Data |   di |   |di| | Rank   | Signed Rank   |
+========+======+========+========+===============+
|    108 |    1 |      1 | 1.0    | +             |
+--------+------+--------+--------+---------------+
|    109 |    2 |      2 | 2.5    | +             |
+--------+------+--------+--------+---------------+
|    105 |   -2 |      2 | 2.5    | -             |
+--------+------+--------+--------+---------------+
|    104 |   -3 |      3 | 4.0    | -             |
+--------+------+--------+--------+---------------+
|    111 |    4 |      4 | 5.0    | +             |
+--------+------+--------+--------+---------------+
|    100 |   -7 |      7 | 6.0    | -             |
+--------+------+--------+--------+---------------+
|     99 |   -8 |      8 | 7.0    | -             |
+--------+------+--------+--------+---------------+
|    117 |   10 |     10 | 8.0    | +             |
+--------+------+--------+--------+---------------+
|    119 |   12 |     12 | 9.0    | +             |
+--------+------+--------+--------+---------------+
|     94 |  -13 |     13 | 10.0   | -             |
+--------+------+--------+--------+---------------+
|     90 |  -17 |     17 | 11.0   | -             |
+--------+------+--------+--------+---------------+
|    125 |   18 |     18 | 12.0   | +             |
+--------+------+--------+--------+---------------+
|    127 |   20 |     20 | 13.0   | +             |
+--------+------+--------+--------+---------------+
|    135 |   28 |     28 | 14.0   | +             |
+--------+------+--------+--------+---------------+
|    107 |    0 |      0 | -      | -             |
+--------+------+--------+--------+---------------+

3. Statistika Uji:
Jumlah peringkat positif: 64.5
Jumlah peringkat negatif: 40.5
Statistik uji Wilcoxon (T): 40.5
Alpha: 0.05
Nilai kritis Wilcoxon (d): 21

4. Penarikan Kesimpulan
Karena T: 40.5 >= d: 21
Kesimpulan: Gagal menolak H0, tidak ada perbedaan yang signifikan antara median data dengan median yang disumsikan.

In [ ]:
a = [83, 67, 80, 75, 86, 75, 81, 70, 68, 66,
     78, 82, 83, 74, 60, 61, 63, 79, 80, 81]
b = [71, 67, 72, 63, 83, 70, 69, 63, 59, 66,
     82, 82, 82, 80, 71, 73, 75, 70, 78, 69]
test_type = 'paired'
alpha = 0.05
wilcoxon_test(test_type, a, b, median_assumption, alpha)

1. Hipotesis:
H0: Tidak ada perbedaan yang signifikan antara kedua sampel
H1: Ada perbedaan yang signifikan antara kedua sampel
+---------+---------+------+--------+--------+---------------+
|   Data1 |   Data2 |   di |   |di| | Rank   | Signed Rank   |
+=========+=========+======+========+========+===============+
|      83 |      82 |    1 |      1 | 1.0    | +             |
+---------+---------+------+--------+--------+---------------+
|      80 |      78 |    2 |      2 | 2.0    | +             |
+---------+---------+------+--------+--------+---------------+
|      86 |      83 |    3 |      3 | 3.0    | +             |
+---------+---------+------+--------+--------+---------------+
|      78 |      82 |   -4 |      4 | 4.0    | -             |
+---------+---------+------+--------+--------+---------------+
|      75 |      70 |    5 |      5 | 5.0    | +             |
+---------+---------+------+--------+--------+---------------+
|      74 |      80 |   -6 |      6 | 6.0    | -             |
+---------+---------+------+--------+--------+---------------+
|      70 |      63 |    7 |      7 | 7.0    | +             |
+---------+---------+------+--------+--------+---------------+
|      80 |      72 |    8 |      8 | 8.0    | +             |
+---------+---------+------+--------+--------+---------------+
|      68 |      59 |    9 |      9 | 9.5    | +             |
+---------+---------+------+--------+--------+---------------+
|      79 |      70 |    9 |      9 | 9.5    | +             |
+---------+---------+------+--------+--------+---------------+
|      60 |      71 |  -11 |     11 | 11.0   | -             |
+---------+---------+------+--------+--------+---------------+
|      83 |      71 |   12 |     12 | 14.5   | +             |
+---------+---------+------+--------+--------+---------------+
|      75 |      63 |   12 |     12 | 14.5   | +             |
+---------+---------+------+--------+--------+---------------+
|      81 |      69 |   12 |     12 | 14.5   | +             |
+---------+---------+------+--------+--------+---------------+
|      61 |      73 |  -12 |     12 | 14.5   | -             |
+---------+---------+------+--------+--------+---------------+
|      63 |      75 |  -12 |     12 | 14.5   | -             |
+---------+---------+------+--------+--------+---------------+
|      81 |      69 |   12 |     12 | 14.5   | +             |
+---------+---------+------+--------+--------+---------------+
|      67 |      67 |    0 |      0 | -      | -             |
+---------+---------+------+--------+--------+---------------+
|      66 |      66 |    0 |      0 | -      | -             |
+---------+---------+------+--------+--------+---------------+
|      82 |      82 |    0 |      0 | -      | -             |
+---------+---------+------+--------+--------+---------------+
2. Kriteria Uji:
Jika T < nilai kritis d, maka tolak H0

3. Statistika Uji:
Jumlah peringkat positif: 103.0
Jumlah peringkat negatif: 50.0
Statistik uji Wilcoxon (T): 50.0
Alpha: 0.05
Nilai kritis Wilcoxon (d): 34

4. Penarikan Kesimpulan
Karena T: 50.0 >= d: 34
Kesimpulan: Gagal menolak H0, tidak ada perbedaan yang signifikan.

## Load Dataset

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### PCOS Dataset

In [ ]:
!unzip /content/drive/MyDrive/dataset/pcos_dataset.zip -d /content/dataset/

Archive:  /content/drive/MyDrive/dataset/pcos_dataset.zip
  inflating: /content/dataset/pcos_dataset.csv

In [ ]:
path = '/content/dataset/pcos_dataset.csv'
data1 = pd.read_csv(path)

In [ ]:
data1

,Age,BMI,Menstrual_Irregularity,Testosterone_Level(ng/dL),Antral_Follicle_Count,PCOS_Diagnosis
0,24,34.7,1,25.2,20,0
1,37,26.4,0,57.1,25,0
2,32,23.6,0,92.7,28,0
3,28,28.8,0,63.1,26,0
4,25,22.1,1,59.8,8,0
...,...,...,...,...,...,...
995,34,18.4,1,95.7,23,0
996,45,28.9,1,28.5,7,0
997,37,28.3,0,32.4,28,0
998,41,27.3,0,95.6,9,0
999,22,21.9,1,78.9,7,0

In [ ]:
data1.columns

Index(['Age', 'BMI', 'Menstrual_Irregularity', 'Testosterone_Level(ng/dL)',
       'Antral_Follicle_Count', 'PCOS_Diagnosis'],
      dtype='object')

In [ ]:
data1.dtypes

Age                            int64
BMI                          float64
Menstrual_Irregularity         int64
Testosterone_Level(ng/dL)    float64
Antral_Follicle_Count          int64
PCOS_Diagnosis                 int64
dtype: object

In [ ]:
pcos_data = data1[data1['PCOS_Diagnosis'] == 1]
pcos_data

,Age,BMI,Menstrual_Irregularity,Testosterone_Level(ng/dL),Antral_Follicle_Count,PCOS_Diagnosis
13,38,33.2,1,43.0,21,1
14,21,26.1,1,83.4,13,1
27,18,26.6,1,42.2,21,1
28,29,29.7,1,98.7,14,1
33,34,32.9,1,72.3,24,1
...,...,...,...,...,...,...
975,44,28.4,1,68.3,16,1
978,37,33.3,1,96.1,20,1
983,32,32.0,1,71.9,18,1
988,34,25.7,1,74.1,28,1
989,22,28.0,1,76.5,26,1

In [ ]:
pcos_data['BMI'].mean()

30.126633165829144

In [ ]:
test_type = 'one_sample'
median_assumption = 30
alpha = 0.05
wilcoxon_test(test_type, pcos_data['BMI'], median_assumption=median_assumption, alpha=alpha, alternative = 'two-sided')

1. Hipotesis:
H0: Tidak ada perbedaan yang signifikan.
H1: Ada perbedaan yang signifikan.
+--------+------+--------+--------+---------------+
|   Data |   di |   |di| | Rank   | Signed Rank   |
+========+======+========+========+===============+
|   29.9 | -0.1 |    0.1 | 1.5    | -             |
+--------+------+--------+--------+---------------+
|   30.1 |  0.1 |    0.1 | 1.5    | +             |
+--------+------+--------+--------+---------------+
|   30.2 |  0.2 |    0.2 | 4.0    | +             |
+--------+------+--------+--------+---------------+
|   29.8 | -0.2 |    0.2 | 4.0    | -             |
+--------+------+--------+--------+---------------+
|   30.2 |  0.2 |    0.2 | 4.0    | +             |
+--------+------+--------+--------+---------------+
|   29.7 | -0.3 |    0.3 | 7.0    | -             |
+--------+------+--------+--------+---------------+
|   30.3 |  0.3 |    0.3 | 7.0    | +             |
+--------+------+--------+--------+---------------+
|   29.7 | -0.3 |    0.3 | 7.0    | -             |
+--------+------+--------+--------+---------------+
|   30.4 |  0.4 |    0.4 | 11.0   | +             |
+--------+------+--------+--------+---------------+
|   29.6 | -0.4 |    0.4 | 11.0   | -             |
+--------+------+--------+--------+---------------+
|   29.6 | -0.4 |    0.4 | 11.0   | -             |
+--------+------+--------+--------+---------------+
|   30.4 |  0.4 |    0.4 | 11.0   | +             |
+--------+------+--------+--------+---------------+
|   29.6 | -0.4 |    0.4 | 11.0   | -             |
+--------+------+--------+--------+---------------+
|   30.5 |  0.5 |    0.5 | 16.0   | +             |
+--------+------+--------+--------+---------------+
|   30.5 |  0.5 |    0.5 | 16.0   | +             |
+--------+------+--------+--------+---------------+
|   29.5 | -0.5 |    0.5 | 16.0   | -             |
+--------+------+--------+--------+---------------+
|   30.5 |  0.5 |    0.5 | 16.0   | +             |
+--------+------+--------+--------+---------------+
|   29.5 | -0.5 |    0.5 | 16.0   | -             |
+--------+------+--------+--------+---------------+
|   29.4 | -0.6 |    0.6 | 21.0   | -             |
+--------+------+--------+--------+---------------+
|   30.6 |  0.6 |    0.6 | 21.0   | +             |
+--------+------+--------+--------+---------------+
|   30.6 |  0.6 |    0.6 | 21.0   | +             |
+--------+------+--------+--------+---------------+
|   29.4 | -0.6 |    0.6 | 21.0   | -             |
+--------+------+--------+--------+---------------+
|   29.4 | -0.6 |    0.6 | 21.0   | -             |
+--------+------+--------+--------+---------------+
|   30.7 |  0.7 |    0.7 | 26.0   | +             |
+--------+------+--------+--------+---------------+
|   30.7 |  0.7 |    0.7 | 26.0   | +             |
+--------+------+--------+--------+---------------+
|   29.3 | -0.7 |    0.7 | 26.0   | -             |
+--------+------+--------+--------+---------------+
|   30.7 |  0.7 |    0.7 | 26.0   | +             |
+--------+------+--------+--------+---------------+
|   29.3 | -0.7 |    0.7 | 26.0   | -             |
+--------+------+--------+--------+---------------+
|   29.2 | -0.8 |    0.8 | 29.0   | -             |
+--------+------+--------+--------+---------------+
|   29.1 | -0.9 |    0.9 | 31.0   | -             |
+--------+------+--------+--------+---------------+
|   30.9 |  0.9 |    0.9 | 31.0   | +             |
+--------+------+--------+--------+---------------+
|   29.1 | -0.9 |    0.9 | 31.0   | -             |
+--------+------+--------+--------+---------------+
|   31.1 |  1.1 |    1.1 | 35.0   | +             |
+--------+------+--------+--------+---------------+
|   28.9 | -1.1 |    1.1 | 35.0   | -             |
+--------+------+--------+--------+---------------+
|   31.1 |  1.1 |    1.1 | 35.0   | +             |
+--------+------+--------+--------+---------------+
|   28.9 | -1.1 |    1.1 | 35.0   | -             |
+--------+------+--------+--------+---------------+
|   31.1 |  1.1 |    1.1 | 35.0   | +             |
+--------+------+--------+--------+---------------+
|   28.7 | -1.3 |    1.3 | 39.0   | -             |
+--------+------+--------+--------+---------------+
|   31.3 |  1.3 |    1.3 | 39.0   | +             |
+--------+------+--------+--------+---------------+
|   31.3 |  1.3 |    1.3 | 39.0   | +             |
+--------+------+--------+--------+---------------+
|   31.4 |  1.4 |    1.4 | 43.5   | +             |
+--------+------+--------+--------+---------------+
|   28.6 | -1.4 |    1.4 | 43.5   | -             |
+--------+------+--------+--------+---------------+
|   31.4 |  1.4 |    1.4 | 43.5   | +             |
+--------+------+--------+--------+---------------+
|   28.6 | -1.4 |    1.4 | 43.5   | -             |
+--------+------+--------+--------+---------------+
|   28.6 | -1.4 |    1.4 | 43.5   | -             |
+--------+------+--------+--------+---------------+
|   28.6 | -1.4 |    1.4 | 43.5   | -             |
+--------+------+--------+--------+---------------+
|   28.5 | -1.5 |    1.5 | 49.5   | -             |
+--------+------+--------+--------+---------------+
|   31.5 |  1.5 |    1.5 | 49.5   | +             |
+--------+------+--------+--------+---------------+
|   28.5 | -1.5 |    1.5 | 49.5   | -             |
+--------+------+--------+--------+---------------+
|   28.5 | -1.5 |    1.5 | 49.5   | -             |
+--------+------+--------+--------+---------------+
|   31.5 |  1.5 |    1.5 | 49.5   | +             |
+--------+------+--------+--------+---------------+
|   28.5 | -1.5 |    1.5 | 49.5   | -             |
+--------+------+--------+--------+---------------+
|   28.4 | -1.6 |    1.6 | 56.5   | -             |
+--------+------+--------+--------+---------------+
|   31.6 |  1.6 |    1.6 | 56.5   | +             |
+--------+------+--------+--------+---------------+
|   31.6 |  1.6 |    1.6 | 56.5   | +             |
+--------+------+--------+--------+---------------+
|   31.6 |  1.6 |    1.6 | 56.5   | +             |
+--------+------+--------+--------+---------------+
|   31.6 |  1.6 |    1.6 | 56.5   | +             |
+--------+------+--------+--------+---------------+
|   31.6 |  1.6 |    1.6 | 56.5   | +             |
+--------+------+--------+--------+---------------+
|   28.4 | -1.6 |    1.6 | 56.5   | -             |
+--------+------+--------+--------+---------------+
|   28.4 | -1.6 |    1.6 | 56.5   | -             |
+--------+------+--------+--------+---------------+
|   28.3 | -1.7 |    1.7 | 62.0   | -             |
+--------+------+--------+--------+---------------+
|   28.3 | -1.7 |    1.7 | 62.0   | -             |
+--------+------+--------+--------+---------------+
|   28.3 | -1.7 |    1.7 | 62.0   | -             |
+--------+------+--------+--------+---------------+
|   31.8 |  1.8 |    1.8 | 65.0   | +             |
+--------+------+--------+--------+---------------+
|   28.2 | -1.8 |    1.8 | 65.0   | -             |
+--------+------+--------+--------+---------------+
|   28.2 | -1.8 |    1.8 | 65.0   | -             |
+--------+------+--------+--------+---------------+
|   28.1 | -1.9 |    1.9 | 70.0   | -             |
+--------+------+--------+--------+---------------+
|   31.9 |  1.9 |    1.9 | 70.0   | +             |
+--------+------+--------+--------+---------------+
|   28.1 | -1.9 |    1.9 | 70.0   | -             |
+--------+------+--------+--------+---------------+
|   31.9 |  1.9 |    1.9 | 70.0   | +             |
+--------+------+--------+--------+---------------+
|   31.9 |  1.9 |    1.9 | 70.0   | +             |
+--------+------+--------+--------+---------------+
|   31.9 |  1.9 |    1.9 | 70.0   | +             |
+--------+------+--------+--------+---------------+
|   31.9 |  1.9 |    1.9 | 70.0   | +             |
+--------+------+--------+--------+---------------+
|   28   | -2   |    2   | 76.5   | -             |
+--------+------+--------+--------+---------------+
|   32   |  2   |    2   | 76.5   | +             |
+--------+------+--------+--------+---------------+
|   28   | -2   |    2   | 76.5   | -             |
+--------+------+--------+--------+---------------+
|   32   |  2   |    2   | 76.5   | +             |
+--------+------+--------+--------+---------------+
|   32   |  2   |    2   | 76.5   | +             |
+--------+------+--------+--------+---------------+
|   28   | -2   |    2   | 76.5   | -             |
+--------+------+--------+--------+---------------+
|   27.9 | -2.1 |    2.1 | 82.0   | -             |
+--------+------+--------+--------+---------------+
|   27.9 | -2.1 |    2.1 | 82.0   | -             |
+--------+------+--------+--------+---------------+
|   32.1 |  2.1 |    2.1 | 82.0   | +             |
+--------+------+--------+--------+---------------+
|   27.9 | -2.1 |    2.1 | 82.0   | -             |
+--------+------+--------+--------+---------------+
|   27.9 | -2.1 |    2.1 | 82.0   | -             |
+--------+------+--------+--------+---------------+
|   32.2 |  2.2 |    2.2 | 85.0   | +             |
+--------+------+--------+--------+---------------+
|   32.3 |  2.3 |    2.3 | 86.5   | +             |
+--------+------+--------+--------+---------------+
|   32.3 |  2.3 |    2.3 | 86.5   | +             |
+--------+------+--------+--------+---------------+
|   27.7 | -2.3 |    2.3 | 88.5   | -             |
+--------+------+--------+--------+---------------+
|   27.7 | -2.3 |    2.3 | 88.5   | -             |
+--------+------+--------+--------+---------------+
|   27.6 | -2.4 |    2.4 | 90.5   | -             |
+--------+------+--------+--------+---------------+
|   27.6 | -2.4 |    2.4 | 90.5   | -             |
+--------+------+--------+--------+---------------+
|   27.5 | -2.5 |    2.5 | 93.0   | -             |
+--------+------+--------+--------+---------------+
|   32.5 |  2.5 |    2.5 | 93.0   | +             |
+--------+------+--------+--------+---------------+
|   27.5 | -2.5 |    2.5 | 93.0   | -             |
+--------+------+--------+--------+---------------+
|   27.4 | -2.6 |    2.6 | 96.0   | -             |
+--------+------+--------+--------+---------------+
|   27.4 | -2.6 |    2.6 | 96.0   | -             |
+--------+------+--------+--------+---------------+
|   27.4 | -2.6 |    2.6 | 96.0   | -             |
+--------+------+--------+--------+---------------+
|   32.7 |  2.7 |    2.7 | 100.0  | +             |
+--------+------+--------+--------+---------------+
|   32.7 |  2.7 |    2.7 | 100.0  | +             |
+--------+------+--------+--------+---------------+
|   32.7 |  2.7 |    2.7 | 100.0  | +             |
+--------+------+--------+--------+---------------+
|   32.7 |  2.7 |    2.7 | 100.0  | +             |
+--------+------+--------+--------+---------------+
|   32.7 |  2.7 |    2.7 | 100.0  | +             |
+--------+------+--------+--------+---------------+
|   32.8 |  2.8 |    2.8 | 106.5  | +             |
+--------+------+--------+--------+---------------+
|   32.8 |  2.8 |    2.8 | 106.5  | +             |
+--------+------+--------+--------+---------------+
|   32.8 |  2.8 |    2.8 | 106.5  | +             |
+--------+------+--------+--------+---------------+
|   32.8 |  2.8 |    2.8 | 106.5  | +             |
+--------+------+--------+--------+---------------+
|   32.8 |  2.8 |    2.8 | 106.5  | +             |
+--------+------+--------+--------+---------------+
|   32.8 |  2.8 |    2.8 | 106.5  | +             |
+--------+------+--------+--------+---------------+
|   32.8 |  2.8 |    2.8 | 106.5  | +             |
+--------+------+--------+--------+---------------+
|   32.8 |  2.8 |    2.8 | 106.5  | +             |
+--------+------+--------+--------+---------------+
|   27.2 | -2.8 |    2.8 | 113.0  | -             |
+--------+------+--------+--------+---------------+
|   27.2 | -2.8 |    2.8 | 113.0  | -             |
+--------+------+--------+--------+---------------+
|   27.2 | -2.8 |    2.8 | 113.0  | -             |
+--------+------+--------+--------+---------------+
|   27.2 | -2.8 |    2.8 | 113.0  | -             |
+--------+------+--------+--------+---------------+
|   27.2 | -2.8 |    2.8 | 113.0  | -             |
+--------+------+--------+--------+---------------+
|   32.9 |  2.9 |    2.9 | 118.5  | +             |
+--------+------+--------+--------+---------------+
|   27.1 | -2.9 |    2.9 | 118.5  | -             |
+--------+------+--------+--------+---------------+
|   32.9 |  2.9 |    2.9 | 118.5  | +             |
+--------+------+--------+--------+---------------+
|   27.1 | -2.9 |    2.9 | 118.5  | -             |
+--------+------+--------+--------+---------------+
|   32.9 |  2.9 |    2.9 | 118.5  | +             |
+--------+------+--------+--------+---------------+
|   32.9 |  2.9 |    2.9 | 118.5  | +             |
+--------+------+--------+--------+---------------+
|   26.9 | -3.1 |    3.1 | 123.5  | -             |
+--------+------+--------+--------+---------------+
|   26.9 | -3.1 |    3.1 | 123.5  | -             |
+--------+------+--------+--------+---------------+
|   26.9 | -3.1 |    3.1 | 123.5  | -             |
+--------+------+--------+--------+---------------+
|   33.1 |  3.1 |    3.1 | 123.5  | +             |
+--------+------+--------+--------+---------------+
|   26.8 | -3.2 |    3.2 | 127.0  | -             |
+--------+------+--------+--------+---------------+
|   26.8 | -3.2 |    3.2 | 127.0  | -             |
+--------+------+--------+--------+---------------+
|   26.8 | -3.2 |    3.2 | 127.0  | -             |
+--------+------+--------+--------+---------------+
|   33.2 |  3.2 |    3.2 | 130.0  | +             |
+--------+------+--------+--------+---------------+
|   33.2 |  3.2 |    3.2 | 130.0  | +             |
+--------+------+--------+--------+---------------+
|   33.2 |  3.2 |    3.2 | 130.0  | +             |
+--------+------+--------+--------+---------------+
|   33.3 |  3.3 |    3.3 | 133.0  | +             |
+--------+------+--------+--------+---------------+
|   33.3 |  3.3 |    3.3 | 133.0  | +             |
+--------+------+--------+--------+---------------+
|   33.3 |  3.3 |    3.3 | 133.0  | +             |
+--------+------+--------+--------+---------------+
|   26.7 | -3.3 |    3.3 | 135.0  | -             |
+--------+------+--------+--------+---------------+
|   26.6 | -3.4 |    3.4 | 136.5  | -             |
+--------+------+--------+--------+---------------+
|   33.4 |  3.4 |    3.4 | 136.5  | +             |
+--------+------+--------+--------+---------------+
|   26.5 | -3.5 |    3.5 | 138.5  | -             |
+--------+------+--------+--------+---------------+
|   33.5 |  3.5 |    3.5 | 138.5  | +             |
+--------+------+--------+--------+---------------+
|   33.6 |  3.6 |    3.6 | 141.5  | +             |
+--------+------+--------+--------+---------------+
|   33.6 |  3.6 |    3.6 | 141.5  | +             |
+--------+------+--------+--------+---------------+
|   26.4 | -3.6 |    3.6 | 141.5  | -             |
+--------+------+--------+--------+---------------+
|   26.4 | -3.6 |    3.6 | 141.5  | -             |
+--------+------+--------+--------+---------------+
|   26.3 | -3.7 |    3.7 | 144.0  | -             |
+--------+------+--------+--------+---------------+
|   33.7 |  3.7 |    3.7 | 145.5  | +             |
+--------+------+--------+--------+---------------+
|   33.7 |  3.7 |    3.7 | 145.5  | +             |
+--------+------+--------+--------+---------------+
|   33.8 |  3.8 |    3.8 | 147.5  | +             |
+--------+------+--------+--------+---------------+
|   33.8 |  3.8 |    3.8 | 147.5  | +             |
+--------+------+--------+--------+---------------+
|   26.2 | -3.8 |    3.8 | 150.0  | -             |
+--------+------+--------+--------+---------------+
|   26.2 | -3.8 |    3.8 | 150.0  | -             |
+--------+------+--------+--------+---------------+
|   26.2 | -3.8 |    3.8 | 150.0  | -             |
+--------+------+--------+--------+---------------+
|   26.1 | -3.9 |    3.9 | 153.0  | -             |
+--------+------+--------+--------+---------------+
|   33.9 |  3.9 |    3.9 | 153.0  | +             |
+--------+------+--------+--------+---------------+
|   33.9 |  3.9 |    3.9 | 153.0  | +             |
+--------+------+--------+--------+---------------+
|   34   |  4   |    4   | 156.0  | +             |
+--------+------+--------+--------+---------------+
|   34   |  4   |    4   | 156.0  | +             |
+--------+------+--------+--------+---------------+
|   34   |  4   |    4   | 156.0  | +             |
+--------+------+--------+--------+---------------+
|   25.9 | -4.1 |    4.1 | 160.5  | -             |
+--------+------+--------+--------+---------------+
|   34.1 |  4.1 |    4.1 | 160.5  | +             |
+--------+------+--------+--------+---------------+
|   34.1 |  4.1 |    4.1 | 160.5  | +             |
+--------+------+--------+--------+---------------+
|   34.1 |  4.1 |    4.1 | 160.5  | +             |
+--------+------+--------+--------+---------------+
|   25.9 | -4.1 |    4.1 | 160.5  | -             |
+--------+------+--------+--------+---------------+
|   34.1 |  4.1 |    4.1 | 160.5  | +             |
+--------+------+--------+--------+---------------+
|   34.2 |  4.2 |    4.2 | 165.0  | +             |
+--------+------+--------+--------+---------------+
|   34.2 |  4.2 |    4.2 | 165.0  | +             |
+--------+------+--------+--------+---------------+
|   34.2 |  4.2 |    4.2 | 165.0  | +             |
+--------+------+--------+--------+---------------+
|   25.7 | -4.3 |    4.3 | 169.0  | -             |
+--------+------+--------+--------+---------------+
|   25.7 | -4.3 |    4.3 | 169.0  | -             |
+--------+------+--------+--------+---------------+
|   25.7 | -4.3 |    4.3 | 169.0  | -             |
+--------+------+--------+--------+---------------+
|   25.7 | -4.3 |    4.3 | 169.0  | -             |
+--------+------+--------+--------+---------------+
|   25.7 | -4.3 |    4.3 | 169.0  | -             |
+--------+------+--------+--------+---------------+
|   34.4 |  4.4 |    4.4 | 173.5  | +             |
+--------+------+--------+--------+---------------+
|   34.4 |  4.4 |    4.4 | 173.5  | +             |
+--------+------+--------+--------+---------------+
|   25.6 | -4.4 |    4.4 | 173.5  | -             |
+--------+------+--------+--------+---------------+
|   34.4 |  4.4 |    4.4 | 173.5  | +             |
+--------+------+--------+--------+---------------+
|   25.5 | -4.5 |    4.5 | 177.5  | -             |
+--------+------+--------+--------+---------------+
|   34.5 |  4.5 |    4.5 | 177.5  | +             |
+--------+------+--------+--------+---------------+
|   34.5 |  4.5 |    4.5 | 177.5  | +             |
+--------+------+--------+--------+---------------+
|   25.5 | -4.5 |    4.5 | 177.5  | -             |
+--------+------+--------+--------+---------------+
|   25.4 | -4.6 |    4.6 | 182.5  | -             |
+--------+------+--------+--------+---------------+
|   25.4 | -4.6 |    4.6 | 182.5  | -             |
+--------+------+--------+--------+---------------+
|   34.6 |  4.6 |    4.6 | 182.5  | +             |
+--------+------+--------+--------+---------------+
|   34.6 |  4.6 |    4.6 | 182.5  | +             |
+--------+------+--------+--------+---------------+
|   34.6 |  4.6 |    4.6 | 182.5  | +             |
+--------+------+--------+--------+---------------+
|   25.4 | -4.6 |    4.6 | 182.5  | -             |
+--------+------+--------+--------+---------------+
|   25.3 | -4.7 |    4.7 | 186.5  | -             |
+--------+------+--------+--------+---------------+
|   25.3 | -4.7 |    4.7 | 186.5  | -             |
+--------+------+--------+--------+---------------+
|   34.7 |  4.7 |    4.7 | 188.0  | +             |
+--------+------+--------+--------+---------------+
|   34.8 |  4.8 |    4.8 | 190.5  | +             |
+--------+------+--------+--------+---------------+
|   34.8 |  4.8 |    4.8 | 190.5  | +             |

### Diabetes Health Indicator Dataset

In [ ]:
!unzip /content/drive/MyDrive/dataset/dhid_dataset.zip -d /content/dataset/

Archive:  /content/drive/MyDrive/dataset/dhid_dataset.zip
  inflating: /content/dataset/diabetes_012_health_indicators_BRFSS2015.csv
  inflating: /content/dataset/diabetes_binary_5050split_health_indicators_BRFSS2015.csv
  inflating: /content/dataset/diabetes_binary_health_indicators_BRFSS2015.csv

In [ ]:
path = '/content/dataset/diabetes_012_health_indicators_BRFSS2015.csv'
data = pd.read_csv(path)

In [ ]:
data

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,45.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,5.0,0.0,1.0,5.0,6.0,7.0
253676,2.0,1.0,1.0,1.0,18.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
253677,0.0,0.0,0.0,1.0,28.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,5.0,2.0
253678,0.0,1.0,0.0,1.0,23.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,7.0,5.0,1.0
253679,2.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

In [ ]:
data.columns

Index(['Diabetes_012', 'HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker',
       'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies',
       'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'GenHlth',
       'MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 'Age', 'Education',
       'Income'],
      dtype='object')

In [ ]:
data.dtypes

Diabetes_012            float64
HighBP                  float64
HighChol                float64
CholCheck               float64
BMI                     float64
Smoker                  float64
Stroke                  float64
HeartDiseaseorAttack    float64
PhysActivity            float64
Fruits                  float64
Veggies                 float64
HvyAlcoholConsump       float64
AnyHealthcare           float64
NoDocbcCost             float64
GenHlth                 float64
MentHlth                float64
PhysHlth                float64
DiffWalk                float64
Sex                     float64
Age                     float64
Education               float64
Income                  float64
dtype: object

In [ ]:
diabetes_data = data[data['Diabetes_012'] == 2]
diabetes_data

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
8,2.0,1.0,1.0,1.0,30.0,1.0,0.0,1.0,0.0,1.0,...,1.0,0.0,5.0,30.0,30.0,1.0,0.0,9.0,5.0,1.0
10,2.0,0.0,0.0,1.0,25.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,13.0,6.0,8.0
13,2.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,4.0,6.0
17,2.0,0.0,0.0,1.0,23.0,1.0,0.0,0.0,1.0,0.0,...,1.0,0.0,2.0,0.0,0.0,0.0,1.0,7.0,5.0,6.0
23,2.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,13.0,5.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253659,2.0,0.0,1.0,1.0,37.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,0.0,0.0,6.0,4.0,1.0
253668,2.0,0.0,1.0,1.0,29.0,1.0,0.0,1.0,0.0,1.0,...,1.0,0.0,2.0,0.0,0.0,1.0,1.0,10.0,3.0,6.0
253670,2.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,0.0,1.0,...,1.0,0.0,5.0,15.0,0.0,1.0,0.0,13.0,6.0,4.0
253676,2.0,1.0,1.0,1.0,18.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
253679,2.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

## Apply Function

### PCOS Dataset

In [ ]:
test_type = 'one_sample'
median_assumption = 30
alpha = 0.05
wilcoxon_test(test_type, pcos_data['BMI'], median_assumption=median_assumption, alpha=alpha, alternative='two-sided')

1. Hipotesis:
H0: Tidak ada perbedaan yang signifikan.
H1: Ada perbedaan yang signifikan.
+--------+------+--------+--------+---------------+
|   Data |   di |   |di| | Rank   | Signed Rank   |
+========+======+========+========+===============+
|   29.9 | -0.1 |    0.1 | 1.5    | -             |
+--------+------+--------+--------+---------------+
|   30.1 |  0.1 |    0.1 | 1.5    | +             |
+--------+------+--------+--------+---------------+
|   30.2 |  0.2 |    0.2 | 4.0    | +             |
+--------+------+--------+--------+---------------+
|   29.8 | -0.2 |    0.2 | 4.0    | -             |
+--------+------+--------+--------+---------------+
|   30.2 |  0.2 |    0.2 | 4.0    | +             |
+--------+------+--------+--------+---------------+
|   29.7 | -0.3 |    0.3 | 7.0    | -             |
+--------+------+--------+--------+---------------+
|   30.3 |  0.3 |    0.3 | 7.0    | +             |
+--------+------+--------+--------+---------------+
|   29.7 | -0.3 |    0.3 | 7.0    | -             |
+--------+------+--------+--------+---------------+
|   30.4 |  0.4 |    0.4 | 11.0   | +             |
+--------+------+--------+--------+---------------+
|   29.6 | -0.4 |    0.4 | 11.0   | -             |
+--------+------+--------+--------+---------------+
|   29.6 | -0.4 |    0.4 | 11.0   | -             |
+--------+------+--------+--------+---------------+
|   30.4 |  0.4 |    0.4 | 11.0   | +             |
+--------+------+--------+--------+---------------+
|   29.6 | -0.4 |    0.4 | 11.0   | -             |
+--------+------+--------+--------+---------------+
|   30.5 |  0.5 |    0.5 | 16.0   | +             |
+--------+------+--------+--------+---------------+
|   30.5 |  0.5 |    0.5 | 16.0   | +             |
+--------+------+--------+--------+---------------+
|   29.5 | -0.5 |    0.5 | 16.0   | -             |
+--------+------+--------+--------+---------------+
|   30.5 |  0.5 |    0.5 | 16.0   | +             |
+--------+------+--------+--------+---------------+
|   29.5 | -0.5 |    0.5 | 16.0   | -             |
+--------+------+--------+--------+---------------+
|   29.4 | -0.6 |    0.6 | 21.0   | -             |
+--------+------+--------+--------+---------------+
|   30.6 |  0.6 |    0.6 | 21.0   | +             |
+--------+------+--------+--------+---------------+
|   30.6 |  0.6 |    0.6 | 21.0   | +             |
+--------+------+--------+--------+---------------+
|   29.4 | -0.6 |    0.6 | 21.0   | -             |
+--------+------+--------+--------+---------------+
|   29.4 | -0.6 |    0.6 | 21.0   | -             |
+--------+------+--------+--------+---------------+
|   30.7 |  0.7 |    0.7 | 26.0   | +             |
+--------+------+--------+--------+---------------+
|   30.7 |  0.7 |    0.7 | 26.0   | +             |
+--------+------+--------+--------+---------------+
|   29.3 | -0.7 |    0.7 | 26.0   | -             |
+--------+------+--------+--------+---------------+
|   30.7 |  0.7 |    0.7 | 26.0   | +             |
+--------+------+--------+--------+---------------+
|   29.3 | -0.7 |    0.7 | 26.0   | -             |
+--------+------+--------+--------+---------------+
|   29.2 | -0.8 |    0.8 | 29.0   | -             |
+--------+------+--------+--------+---------------+
|   29.1 | -0.9 |    0.9 | 31.0   | -             |
+--------+------+--------+--------+---------------+
|   30.9 |  0.9 |    0.9 | 31.0   | +             |
+--------+------+--------+--------+---------------+
|   29.1 | -0.9 |    0.9 | 31.0   | -             |
+--------+------+--------+--------+---------------+
|   31.1 |  1.1 |    1.1 | 35.0   | +             |
+--------+------+--------+--------+---------------+
|   28.9 | -1.1 |    1.1 | 35.0   | -             |
+--------+------+--------+--------+---------------+
|   31.1 |  1.1 |    1.1 | 35.0   | +             |
+--------+------+--------+--------+---------------+
|   28.9 | -1.1 |    1.1 | 35.0   | -             |
+--------+------+--------+--------+---------------+
|   31.1 |  1.1 |    1.1 | 35.0   | +             |
+--------+------+--------+--------+---------------+
|   28.7 | -1.3 |    1.3 | 39.0   | -             |
+--------+------+--------+--------+---------------+
|   31.3 |  1.3 |    1.3 | 39.0   | +             |
+--------+------+--------+--------+---------------+
|   31.3 |  1.3 |    1.3 | 39.0   | +             |
+--------+------+--------+--------+---------------+
|   31.4 |  1.4 |    1.4 | 43.5   | +             |
+--------+------+--------+--------+---------------+
|   28.6 | -1.4 |    1.4 | 43.5   | -             |
+--------+------+--------+--------+---------------+
|   31.4 |  1.4 |    1.4 | 43.5   | +             |
+--------+------+--------+--------+---------------+
|   28.6 | -1.4 |    1.4 | 43.5   | -             |
+--------+------+--------+--------+---------------+
|   28.6 | -1.4 |    1.4 | 43.5   | -             |
+--------+------+--------+--------+---------------+
|   28.6 | -1.4 |    1.4 | 43.5   | -             |
+--------+------+--------+--------+---------------+
|   28.5 | -1.5 |    1.5 | 49.5   | -             |
+--------+------+--------+--------+---------------+
|   31.5 |  1.5 |    1.5 | 49.5   | +             |
+--------+------+--------+--------+---------------+
|   28.5 | -1.5 |    1.5 | 49.5   | -             |
+--------+------+--------+--------+---------------+
|   28.5 | -1.5 |    1.5 | 49.5   | -             |
+--------+------+--------+--------+---------------+
|   31.5 |  1.5 |    1.5 | 49.5   | +             |
+--------+------+--------+--------+---------------+
|   28.5 | -1.5 |    1.5 | 49.5   | -             |
+--------+------+--------+--------+---------------+
|   28.4 | -1.6 |    1.6 | 56.5   | -             |
+--------+------+--------+--------+---------------+
|   31.6 |  1.6 |    1.6 | 56.5   | +             |
+--------+------+--------+--------+---------------+
|   31.6 |  1.6 |    1.6 | 56.5   | +             |
+--------+------+--------+--------+---------------+
|   31.6 |  1.6 |    1.6 | 56.5   | +             |
+--------+------+--------+--------+---------------+
|   31.6 |  1.6 |    1.6 | 56.5   | +             |
+--------+------+--------+--------+---------------+
|   31.6 |  1.6 |    1.6 | 56.5   | +             |
+--------+------+--------+--------+---------------+
|   28.4 | -1.6 |    1.6 | 56.5   | -             |
+--------+------+--------+--------+---------------+
|   28.4 | -1.6 |    1.6 | 56.5   | -             |
+--------+------+--------+--------+---------------+
|   28.3 | -1.7 |    1.7 | 62.0   | -             |
+--------+------+--------+--------+---------------+
|   28.3 | -1.7 |    1.7 | 62.0   | -             |
+--------+------+--------+--------+---------------+
|   28.3 | -1.7 |    1.7 | 62.0   | -             |
+--------+------+--------+--------+---------------+
|   31.8 |  1.8 |    1.8 | 65.0   | +             |
+--------+------+--------+--------+---------------+
|   28.2 | -1.8 |    1.8 | 65.0   | -             |
+--------+------+--------+--------+---------------+
|   28.2 | -1.8 |    1.8 | 65.0   | -             |
+--------+------+--------+--------+---------------+
|   28.1 | -1.9 |    1.9 | 70.0   | -             |
+--------+------+--------+--------+---------------+
|   31.9 |  1.9 |    1.9 | 70.0   | +             |
+--------+------+--------+--------+---------------+
|   28.1 | -1.9 |    1.9 | 70.0   | -             |
+--------+------+--------+--------+---------------+
|   31.9 |  1.9 |    1.9 | 70.0   | +             |
+--------+------+--------+--------+---------------+
|   31.9 |  1.9 |    1.9 | 70.0   | +             |
+--------+------+--------+--------+---------------+
|   31.9 |  1.9 |    1.9 | 70.0   | +             |
+--------+------+--------+--------+---------------+
|   31.9 |  1.9 |    1.9 | 70.0   | +             |
+--------+------+--------+--------+---------------+
|   28   | -2   |    2   | 76.5   | -             |
+--------+------+--------+--------+---------------+
|   32   |  2   |    2   | 76.5   | +             |
+--------+------+--------+--------+---------------+
|   28   | -2   |    2   | 76.5   | -             |
+--------+------+--------+--------+---------------+
|   32   |  2   |    2   | 76.5   | +             |
+--------+------+--------+--------+---------------+
|   32   |  2   |    2   | 76.5   | +             |
+--------+------+--------+--------+---------------+
|   28   | -2   |    2   | 76.5   | -             |
+--------+------+--------+--------+---------------+
|   27.9 | -2.1 |    2.1 | 82.0   | -             |
+--------+------+--------+--------+---------------+
|   27.9 | -2.1 |    2.1 | 82.0   | -             |
+--------+------+--------+--------+---------------+
|   32.1 |  2.1 |    2.1 | 82.0   | +             |
+--------+------+--------+--------+---------------+
|   27.9 | -2.1 |    2.1 | 82.0   | -             |
+--------+------+--------+--------+---------------+
|   27.9 | -2.1 |    2.1 | 82.0   | -             |
+--------+------+--------+--------+---------------+
|   32.2 |  2.2 |    2.2 | 85.0   | +             |
+--------+------+--------+--------+---------------+
|   32.3 |  2.3 |    2.3 | 86.5   | +             |
+--------+------+--------+--------+---------------+
|   32.3 |  2.3 |    2.3 | 86.5   | +             |
+--------+------+--------+--------+---------------+
|   27.7 | -2.3 |    2.3 | 88.5   | -             |
+--------+------+--------+--------+---------------+
|   27.7 | -2.3 |    2.3 | 88.5   | -             |
+--------+------+--------+--------+---------------+
|   27.6 | -2.4 |    2.4 | 90.5   | -             |
+--------+------+--------+--------+---------------+
|   27.6 | -2.4 |    2.4 | 90.5   | -             |
+--------+------+--------+--------+---------------+
|   27.5 | -2.5 |    2.5 | 93.0   | -             |
+--------+------+--------+--------+---------------+
|   32.5 |  2.5 |    2.5 | 93.0   | +             |
+--------+------+--------+--------+---------------+
|   27.5 | -2.5 |    2.5 | 93.0   | -             |
+--------+------+--------+--------+---------------+
|   27.4 | -2.6 |    2.6 | 96.0   | -             |
+--------+------+--------+--------+---------------+
|   27.4 | -2.6 |    2.6 | 96.0   | -             |
+--------+------+--------+--------+---------------+
|   27.4 | -2.6 |    2.6 | 96.0   | -             |
+--------+------+--------+--------+---------------+
|   32.7 |  2.7 |    2.7 | 100.0  | +             |
+--------+------+--------+--------+---------------+
|   32.7 |  2.7 |    2.7 | 100.0  | +             |
+--------+------+--------+--------+---------------+
|   32.7 |  2.7 |    2.7 | 100.0  | +             |
+--------+------+--------+--------+---------------+
|   32.7 |  2.7 |    2.7 | 100.0  | +             |
+--------+------+--------+--------+---------------+
|   32.7 |  2.7 |    2.7 | 100.0  | +             |
+--------+------+--------+--------+---------------+
|   32.8 |  2.8 |    2.8 | 106.5  | +             |
+--------+------+--------+--------+---------------+
|   32.8 |  2.8 |    2.8 | 106.5  | +             |
+--------+------+--------+--------+---------------+
|   32.8 |  2.8 |    2.8 | 106.5  | +             |
+--------+------+--------+--------+---------------+
|   32.8 |  2.8 |    2.8 | 106.5  | +             |
+--------+------+--------+--------+---------------+
|   32.8 |  2.8 |    2.8 | 106.5  | +             |
+--------+------+--------+--------+---------------+
|   32.8 |  2.8 |    2.8 | 106.5  | +             |
+--------+------+--------+--------+---------------+
|   32.8 |  2.8 |    2.8 | 106.5  | +             |
+--------+------+--------+--------+---------------+
|   32.8 |  2.8 |    2.8 | 106.5  | +             |
+--------+------+--------+--------+---------------+
|   27.2 | -2.8 |    2.8 | 113.0  | -             |
+--------+------+--------+--------+---------------+
|   27.2 | -2.8 |    2.8 | 113.0  | -             |
+--------+------+--------+--------+---------------+
|   27.2 | -2.8 |    2.8 | 113.0  | -             |
+--------+------+--------+--------+---------------+
|   27.2 | -2.8 |    2.8 | 113.0  | -             |
+--------+------+--------+--------+---------------+
|   27.2 | -2.8 |    2.8 | 113.0  | -             |
+--------+------+--------+--------+---------------+
|   32.9 |  2.9 |    2.9 | 118.5  | +             |
+--------+------+--------+--------+---------------+
|   27.1 | -2.9 |    2.9 | 118.5  | -             |
+--------+------+--------+--------+---------------+
|   32.9 |  2.9 |    2.9 | 118.5  | +             |
+--------+------+--------+--------+---------------+
|   27.1 | -2.9 |    2.9 | 118.5  | -             |
+--------+------+--------+--------+---------------+
|   32.9 |  2.9 |    2.9 | 118.5  | +             |
+--------+------+--------+--------+---------------+
|   32.9 |  2.9 |    2.9 | 118.5  | +             |
+--------+------+--------+--------+---------------+
|   26.9 | -3.1 |    3.1 | 123.5  | -             |
+--------+------+--------+--------+---------------+
|   26.9 | -3.1 |    3.1 | 123.5  | -             |
+--------+------+--------+--------+---------------+
|   26.9 | -3.1 |    3.1 | 123.5  | -             |
+--------+------+--------+--------+---------------+
|   33.1 |  3.1 |    3.1 | 123.5  | +             |
+--------+------+--------+--------+---------------+
|   26.8 | -3.2 |    3.2 | 127.0  | -             |
+--------+------+--------+--------+---------------+
|   26.8 | -3.2 |    3.2 | 127.0  | -             |
+--------+------+--------+--------+---------------+
|   26.8 | -3.2 |    3.2 | 127.0  | -             |
+--------+------+--------+--------+---------------+
|   33.2 |  3.2 |    3.2 | 130.0  | +             |
+--------+------+--------+--------+---------------+
|   33.2 |  3.2 |    3.2 | 130.0  | +             |
+--------+------+--------+--------+---------------+
|   33.2 |  3.2 |    3.2 | 130.0  | +             |
+--------+------+--------+--------+---------------+
|   33.3 |  3.3 |    3.3 | 133.0  | +             |
+--------+------+--------+--------+---------------+
|   33.3 |  3.3 |    3.3 | 133.0  | +             |
+--------+------+--------+--------+---------------+
|   33.3 |  3.3 |    3.3 | 133.0  | +             |
+--------+------+--------+--------+---------------+
|   26.7 | -3.3 |    3.3 | 135.0  | -             |
+--------+------+--------+--------+---------------+
|   26.6 | -3.4 |    3.4 | 136.5  | -             |
+--------+------+--------+--------+---------------+
|   33.4 |  3.4 |    3.4 | 136.5  | +             |
+--------+------+--------+--------+---------------+
|   26.5 | -3.5 |    3.5 | 138.5  | -             |
+--------+------+--------+--------+---------------+
|   33.5 |  3.5 |    3.5 | 138.5  | +             |
+--------+------+--------+--------+---------------+
|   33.6 |  3.6 |    3.6 | 141.5  | +             |
+--------+------+--------+--------+---------------+
|   33.6 |  3.6 |    3.6 | 141.5  | +             |
+--------+------+--------+--------+---------------+
|   26.4 | -3.6 |    3.6 | 141.5  | -             |
+--------+------+--------+--------+---------------+
|   26.4 | -3.6 |    3.6 | 141.5  | -             |
+--------+------+--------+--------+---------------+
|   26.3 | -3.7 |    3.7 | 144.0  | -             |
+--------+------+--------+--------+---------------+
|   33.7 |  3.7 |    3.7 | 145.5  | +             |
+--------+------+--------+--------+---------------+
|   33.7 |  3.7 |    3.7 | 145.5  | +             |
+--------+------+--------+--------+---------------+
|   33.8 |  3.8 |    3.8 | 147.5  | +             |
+--------+------+--------+--------+---------------+
|   33.8 |  3.8 |    3.8 | 147.5  | +             |
+--------+------+--------+--------+---------------+
|   26.2 | -3.8 |    3.8 | 150.0  | -             |
+--------+------+--------+--------+---------------+
|   26.2 | -3.8 |    3.8 | 150.0  | -             |
+--------+------+--------+--------+---------------+
|   26.2 | -3.8 |    3.8 | 150.0  | -             |
+--------+------+--------+--------+---------------+
|   26.1 | -3.9 |    3.9 | 153.0  | -             |
+--------+------+--------+--------+---------------+
|   33.9 |  3.9 |    3.9 | 153.0  | +             |
+--------+------+--------+--------+---------------+
|   33.9 |  3.9 |    3.9 | 153.0  | +             |
+--------+------+--------+--------+---------------+
|   34   |  4   |    4   | 156.0  | +             |
+--------+------+--------+--------+---------------+
|   34   |  4   |    4   | 156.0  | +             |
+--------+------+--------+--------+---------------+
|   34   |  4   |    4   | 156.0  | +             |
+--------+------+--------+--------+---------------+
|   25.9 | -4.1 |    4.1 | 160.5  | -             |
+--------+------+--------+--------+---------------+
|   34.1 |  4.1 |    4.1 | 160.5  | +             |
+--------+------+--------+--------+---------------+
|   34.1 |  4.1 |    4.1 | 160.5  | +             |
+--------+------+--------+--------+---------------+
|   34.1 |  4.1 |    4.1 | 160.5  | +             |
+--------+------+--------+--------+---------------+
|   25.9 | -4.1 |    4.1 | 160.5  | -             |
+--------+------+--------+--------+---------------+
|   34.1 |  4.1 |    4.1 | 160.5  | +             |
+--------+------+--------+--------+---------------+
|   34.2 |  4.2 |    4.2 | 165.0  | +             |
+--------+------+--------+--------+---------------+
|   34.2 |  4.2 |    4.2 | 165.0  | +             |
+--------+------+--------+--------+---------------+
|   34.2 |  4.2 |    4.2 | 165.0  | +             |
+--------+------+--------+--------+---------------+
|   25.7 | -4.3 |    4.3 | 169.0  | -             |
+--------+------+--------+--------+---------------+
|   25.7 | -4.3 |    4.3 | 169.0  | -             |
+--------+------+--------+--------+---------------+
|   25.7 | -4.3 |    4.3 | 169.0  | -             |
+--------+------+--------+--------+---------------+
|   25.7 | -4.3 |    4.3 | 169.0  | -             |
+--------+------+--------+--------+---------------+
|   25.7 | -4.3 |    4.3 | 169.0  | -             |
+--------+------+--------+--------+---------------+
|   34.4 |  4.4 |    4.4 | 173.5  | +             |
+--------+------+--------+--------+---------------+
|   34.4 |  4.4 |    4.4 | 173.5  | +             |
+--------+------+--------+--------+---------------+
|   25.6 | -4.4 |    4.4 | 173.5  | -             |
+--------+------+--------+--------+---------------+
|   34.4 |  4.4 |    4.4 | 173.5  | +             |
+--------+------+--------+--------+---------------+
|   25.5 | -4.5 |    4.5 | 177.5  | -             |
+--------+------+--------+--------+---------------+
|   34.5 |  4.5 |    4.5 | 177.5  | +             |
+--------+------+--------+--------+---------------+
|   34.5 |  4.5 |    4.5 | 177.5  | +             |
+--------+------+--------+--------+---------------+
|   25.5 | -4.5 |    4.5 | 177.5  | -             |
+--------+------+--------+--------+---------------+
|   25.4 | -4.6 |    4.6 | 182.5  | -             |
+--------+------+--------+--------+---------------+
|   25.4 | -4.6 |    4.6 | 182.5  | -             |
+--------+------+--------+--------+---------------+
|   34.6 |  4.6 |    4.6 | 182.5  | +             |
+--------+------+--------+--------+---------------+
|   34.6 |  4.6 |    4.6 | 182.5  | +             |
+--------+------+--------+--------+---------------+
|   34.6 |  4.6 |    4.6 | 182.5  | +             |
+--------+------+--------+--------+---------------+
|   25.4 | -4.6 |    4.6 | 182.5  | -             |
+--------+------+--------+--------+---------------+
|   25.3 | -4.7 |    4.7 | 186.5  | -             |
+--------+------+--------+--------+---------------+
|   25.3 | -4.7 |    4.7 | 186.5  | -             |
+--------+------+--------+--------+---------------+
|   34.7 |  4.7 |    4.7 | 188.0  | +             |
+--------+------+--------+--------+---------------+
|   34.8 |  4.8 |    4.8 | 190.5  | +             |
+--------+------+--------+--------+---------------+
|   34.8 |  4.8 |    4.8 | 190.5  | +             |

### DHI Dataset

In [ ]:
test_type = 'one_sample'
median_assumption = 30
alpha = 0.05
wilcoxon_test(test_type, diabetes_data['BMI'], median_assumption=median_assumption, alpha=alpha, alternative='two-sided')

Output streaming akan dipotong hingga 5000 baris terakhir.
+--------+------+--------+---------+---------------+
|     61 |   31 |     31 | 32860.5 | +             |
+--------+------+--------+---------+---------------+
|     61 |   31 |     31 | 32860.5 | +             |
+--------+------+--------+---------+---------------+
|     61 |   31 |     31 | 32860.5 | +             |
+--------+------+--------+---------+---------------+
|     61 |   31 |     31 | 32860.5 | +             |
+--------+------+--------+---------+---------------+
|     61 |   31 |     31 | 32860.5 | +             |
+--------+------+--------+---------+---------------+
|     61 |   31 |     31 | 32860.5 | +             |
+--------+------+--------+---------+---------------+
|     61 |   31 |     31 | 32860.5 | +             |
+--------+------+--------+---------+---------------+
|     61 |   31 |     31 | 32860.5 | +             |
+--------+------+--------+---------+---------------+
|     61 |   31 |     31 | 32860.5 | +             |
+--------+------+--------+---------+---------------+
|     61 |   31 |     31 | 32860.5 | +             |
+--------+------+--------+---------+---------------+
|     61 |   31 |     31 | 32860.5 | +             |
+--------+------+--------+---------+---------------+
|     61 |   31 |     31 | 32860.5 | +             |
+--------+------+--------+---------+---------------+
|     61 |   31 |     31 | 32860.5 | +             |
+--------+------+--------+---------+---------------+
|     61 |   31 |     31 | 32860.5 | +             |
+--------+------+--------+---------+---------------+
|     62 |   32 |     32 | 32875.5 | +             |
+--------+------+--------+---------+---------------+
|     62 |   32 |     32 | 32875.5 | +             |
+--------+------+--------+---------+---------------+
|     62 |   32 |     32 | 32875.5 | +             |
+--------+------+--------+---------+---------------+
|     62 |   32 |     32 | 32875.5 | +             |
+--------+------+--------+---------+---------------+
|     62 |   32 |     32 | 32875.5 | +             |
+--------+------+--------+---------+---------------+
|     62 |   32 |     32 | 32875.5 | +             |
+--------+------+--------+---------+---------------+
|     62 |   32 |     32 | 32875.5 | +             |
+--------+------+--------+---------+---------------+
|     62 |   32 |     32 | 32875.5 | +             |
+--------+------+--------+---------+---------------+
|     62 |   32 |     32 | 32875.5 | +             |
+--------+------+--------+---------+---------------+
|     62 |   32 |     32 | 32875.5 | +             |
+--------+------+--------+---------+---------------+
|     62 |   32 |     32 | 32875.5 | +             |
+--------+------+--------+---------+---------------+
|     62 |   32 |     32 | 32875.5 | +             |
+--------+------+--------+---------+---------------+
|     62 |   32 |     32 | 32875.5 | +             |
+--------+------+--------+---------+---------------+
|     62 |   32 |     32 | 32875.5 | +             |
+--------+------+--------+---------+---------------+
|     62 |   32 |     32 | 32875.5 | +             |
+--------+------+--------+---------+---------------+
|     62 |   32 |     32 | 32875.5 | +             |
+--------+------+--------+---------+---------------+
|     63 |   33 |     33 | 32892.5 | +             |
+--------+------+--------+---------+---------------+
|     63 |   33 |     33 | 32892.5 | +             |
+--------+------+--------+---------+---------------+
|     63 |   33 |     33 | 32892.5 | +             |
+--------+------+--------+---------+---------------+
|     63 |   33 |     33 | 32892.5 | +             |
+--------+------+--------+---------+---------------+
|     63 |   33 |     33 | 32892.5 | +             |
+--------+------+--------+---------+---------------+
|     63 |   33 |     33 | 32892.5 | +             |
+--------+------+--------+---------+---------------+
|     63 |   33 |     33 | 32892.5 | +             |
+--------+------+--------+---------+---------------+
|     63 |   33 |     33 | 32892.5 | +             |
+--------+------+--------+---------+---------------+
|     63 |   33 |     33 | 32892.5 | +             |
+--------+------+--------+---------+---------------+
|     63 |   33 |     33 | 32892.5 | +             |
+--------+------+--------+---------+---------------+
|     63 |   33 |     33 | 32892.5 | +             |
+--------+------+--------+---------+---------------+
|     63 |   33 |     33 | 32892.5 | +             |
+--------+------+--------+---------+---------------+
|     63 |   33 |     33 | 32892.5 | +             |
+--------+------+--------+---------+---------------+
|     63 |   33 |     33 | 32892.5 | +             |
+--------+------+--------+---------+---------------+
|     63 |   33 |     33 | 32892.5 | +             |
+--------+------+--------+---------+---------------+
|     63 |   33 |     33 | 32892.5 | +             |
+--------+------+--------+---------+---------------+
|     63 |   33 |     33 | 32892.5 | +             |
+--------+------+--------+---------+---------------+
|     63 |   33 |     33 | 32892.5 | +             |
+--------+------+--------+---------+---------------+
|     64 |   34 |     34 | 32905.5 | +             |
+--------+------+--------+---------+---------------+
|     64 |   34 |     34 | 32905.5 | +             |
+--------+------+--------+---------+---------------+
|     64 |   34 |     34 | 32905.5 | +             |
+--------+------+--------+---------+---------------+
|     64 |   34 |     34 | 32905.5 | +             |
+--------+------+--------+---------+---------------+
|     64 |   34 |     34 | 32905.5 | +             |
+--------+------+--------+---------+---------------+
|     64 |   34 |     34 | 32905.5 | +             |
+--------+------+--------+---------+---------------+
|     64 |   34 |     34 | 32905.5 | +             |
+--------+------+--------+---------+---------------+
|     64 |   34 |     34 | 32905.5 | +             |
+--------+------+--------+---------+---------------+
|     65 |   35 |     35 | 32914.5 | +             |
+--------+------+--------+---------+---------------+
|     65 |   35 |     35 | 32914.5 | +             |
+--------+------+--------+---------+---------------+
|     65 |   35 |     35 | 32914.5 | +             |
+--------+------+--------+---------+---------------+
|     65 |   35 |     35 | 32914.5 | +             |
+--------+------+--------+---------+---------------+
|     65 |   35 |     35 | 32914.5 | +             |
+--------+------+--------+---------+---------------+
|     65 |   35 |     35 | 32914.5 | +             |
+--------+------+--------+---------+---------------+
|     65 |   35 |     35 | 32914.5 | +             |
+--------+------+--------+---------+---------------+
|     65 |   35 |     35 | 32914.5 | +             |
+--------+------+--------+---------+---------------+
|     65 |   35 |     35 | 32914.5 | +             |
+--------+------+--------+---------+---------------+
|     65 |   35 |     35 | 32914.5 | +             |
+--------+------+--------+---------+---------------+
|     66 |   36 |     36 | 32924.0 | +             |
+--------+------+--------+---------+---------------+
|     66 |   36 |     36 | 32924.0 | +             |
+--------+------+--------+---------+---------------+
|     66 |   36 |     36 | 32924.0 | +             |
+--------+------+--------+---------+---------------+
|     66 |   36 |     36 | 32924.0 | +             |
+--------+------+--------+---------+---------------+
|     66 |   36 |     36 | 32924.0 | +             |
+--------+------+--------+---------+---------------+
|     66 |   36 |     36 | 32924.0 | +             |
+--------+------+--------+---------+---------------+
|     66 |   36 |     36 | 32924.0 | +             |
+--------+------+--------+---------+---------------+
|     66 |   36 |     36 | 32924.0 | +             |
+--------+------+--------+---------+---------------+
|     66 |   36 |     36 | 32924.0 | +             |
+--------+------+--------+---------+---------------+
|     67 |   37 |     37 | 32931.5 | +             |
+--------+------+--------+---------+---------------+
|     67 |   37 |     37 | 32931.5 | +             |
+--------+------+--------+---------+---------------+
|     67 |   37 |     37 | 32931.5 | +             |
+--------+------+--------+---------+---------------+
|     67 |   37 |     37 | 32931.5 | +             |
+--------+------+--------+---------+---------------+
|     67 |   37 |     37 | 32931.5 | +             |
+--------+------+--------+---------+---------------+
|     67 |   37 |     37 | 32931.5 | +             |
+--------+------+--------+---------+---------------+
|     68 |   38 |     38 | 32937.5 | +             |
+--------+------+--------+---------+---------------+
|     68 |   38 |     38 | 32937.5 | +             |
+--------+------+--------+---------+---------------+
|     68 |   38 |     38 | 32937.5 | +             |
+--------+------+--------+---------+---------------+
|     68 |   38 |     38 | 32937.5 | +             |
+--------+------+--------+---------+---------------+
|     68 |   38 |     38 | 32937.5 | +             |
+--------+------+--------+---------+---------------+
|     68 |   38 |     38 | 32937.5 | +             |
+--------+------+--------+---------+---------------+
|     69 |   39 |     39 | 32942.0 | +             |
+--------+------+--------+---------+---------------+
|     69 |   39 |     39 | 32942.0 | +             |
+--------+------+--------+---------+---------------+
|     69 |   39 |     39 | 32942.0 | +             |
+--------+------+--------+---------+---------------+
|     70 |   40 |     40 | 32946.0 | +             |
+--------+------+--------+---------+---------------+
|     70 |   40 |     40 | 32946.0 | +             |
+--------+------+--------+---------+---------------+
|     70 |   40 |     40 | 32946.0 | +             |
+--------+------+--------+---------+---------------+
|     70 |   40 |     40 | 32946.0 | +             |
+--------+------+--------+---------+---------------+
|     70 |   40 |     40 | 32946.0 | +             |
+--------+------+--------+---------+---------------+
|     71 |   41 |     41 | 32951.0 | +             |
+--------+------+--------+---------+---------------+
|     71 |   41 |     41 | 32951.0 | +             |
+--------+------+--------+---------+---------------+
|     71 |   41 |     41 | 32951.0 | +             |
+--------+------+--------+---------+---------------+
|     71 |   41 |     41 | 32951.0 | +             |
+--------+------+--------+---------+---------------+
|     71 |   41 |     41 | 32951.0 | +             |
+--------+------+--------+---------+---------------+
|     72 |   42 |     42 | 32957.0 | +             |
+--------+------+--------+---------+---------------+
|     72 |   42 |     42 | 32957.0 | +             |
+--------+------+--------+---------+---------------+
|     72 |   42 |     42 | 32957.0 | +             |
+--------+------+--------+---------+---------------+
|     72 |   42 |     42 | 32957.0 | +             |
+--------+------+--------+---------+---------------+
|     72 |   42 |     42 | 32957.0 | +             |
+--------+------+--------+---------+---------------+
|     72 |   42 |     42 | 32957.0 | +             |
+--------+------+--------+---------+---------------+
|     72 |   42 |     42 | 32957.0 | +             |
+--------+------+--------+---------+---------------+
|     73 |   43 |     43 | 32962.0 | +             |
+--------+------+--------+---------+---------------+
|     73 |   43 |     43 | 32962.0 | +             |
+--------+------+--------+---------+---------------+
|     73 |   43 |     43 | 32962.0 | +             |
+--------+------+--------+---------+---------------+
|     74 |   44 |     44 | 32964.0 | +             |
+--------+------+--------+---------+---------------+
|     75 |   45 |     45 | 32967.5 | +             |
+--------+------+--------+---------+---------------+
|     75 |   45 |     45 | 32967.5 | +             |
+--------+------+--------+---------+---------------+
|     75 |   45 |     45 | 32967.5 | +             |
+--------+------+--------+---------+---------------+
|     75 |   45 |     45 | 32967.5 | +             |
+--------+------+--------+---------+---------------+
|     75 |   45 |     45 | 32967.5 | +             |
+--------+------+--------+---------+---------------+
|     75 |   45 |     45 | 32967.5 | +             |
+--------+------+--------+---------+---------------+
|     77 |   47 |     47 | 32974.0 | +             |
+--------+------+--------+---------+---------------+
|     77 |   47 |     47 | 32974.0 | +             |
+--------+------+--------+---------+---------------+
|     77 |   47 |     47 | 32974.0 | +             |
+--------+------+--------+---------+---------------+
|     77 |   47 |     47 | 32974.0 | +             |
+--------+------+--------+---------+---------------+
|     77 |   47 |     47 | 32974.0 | +             |
+--------+------+--------+---------+---------------+
|     77 |   47 |     47 | 32974.0 | +             |
+--------+------+--------+---------+---------------+
|     77 |   47 |     47 | 32974.0 | +             |
+--------+------+--------+---------+---------------+
|     78 |   48 |     48 | 32978.0 | +             |
+--------+------+--------+---------+---------------+
|     79 |   49 |     49 | 32980.5 | +             |
+--------+------+--------+---------+---------------+
|     79 |   49 |     49 | 32980.5 | +             |
+--------+------+--------+---------+---------------+
|     79 |   49 |     49 | 32980.5 | +             |
+--------+------+--------+---------+---------------+
|     79 |   49 |     49 | 32980.5 | +             |
+--------+------+--------+---------+---------------+
|     80 |   50 |     50 | 32983.0 | +             |
+--------+------+--------+---------+---------------+
|     81 |   51 |     51 | 32987.0 | +             |
+--------+------+--------+---------+---------------+
|     81 |   51 |     51 | 32987.0 | +             |
+--------+------+--------+---------+---------------+
|     81 |   51 |     51 | 32987.0 | +             |
+--------+------+--------+---------+---------------+
|     81 |   51 |     51 | 32987.0 | +             |
+--------+------+--------+---------+---------------+
|     81 |   51 |     51 | 32987.0 | +             |
+--------+------+--------+---------+---------------+
|     81 |   51 |     51 | 32987.0 | +             |
+--------+------+--------+---------+---------------+
|     81 |   51 |     51 | 32987.0 | +             |
+--------+------+--------+---------+---------------+
|     82 |   52 |     52 | 32993.5 | +             |
+--------+------+--------+---------+---------------+
|     82 |   52 |     52 | 32993.5 | +             |
+--------+------+--------+---------+---------------+
|     82 |   52 |     52 | 32993.5 | +             |
+--------+------+--------+---------+---------------+
|     82 |   52 |     52 | 32993.5 | +             |
+--------+------+--------+---------+---------------+
|     82 |   52 |     52 | 32993.5 | +             |
+--------+------+--------+---------+---------------+
|     82 |   52 |     52 | 32993.5 | +             |
+--------+------+--------+---------+---------------+
|     83 |   53 |     53 | 32997.0 | +             |
+--------+------+--------+---------+---------------+
|     84 |   54 |     54 | 33000.0 | +             |
+--------+------+--------+---------+---------------+
|     84 |   54 |     54 | 33000.0 | +             |
+--------+------+--------+---------+---------------+
|     84 |   54 |     54 | 33000.0 | +             |
+--------+------+--------+---------+---------------+
|     84 |   54 |     54 | 33000.0 | +             |
+--------+------+--------+---------+---------------+
|     84 |   54 |     54 | 33000.0 | +             |
+--------+------+--------+---------+---------------+
|     85 |   55 |     55 | 33003.0 | +             |
+--------+------+--------+---------+---------------+
|     87 |   57 |     57 | 33008.0 | +             |
+--------+------+--------+---------+---------------+
|     87 |   57 |     57 | 33008.0 | +             |
+--------+------+--------+---------+---------------+
|     87 |   57 |     57 | 33008.0 | +             |
+--------+------+--------+---------+---------------+
|     87 |   57 |     57 | 33008.0 | +             |
+--------+------+--------+---------+---------------+
|     87 |   57 |     57 | 33008.0 | +             |
+--------+------+--------+---------+---------------+
|     87 |   57 |     57 | 33008.0 | +             |
+--------+------+--------+---------+---------------+
|     87 |   57 |     57 | 33008.0 | +             |
+--------+------+--------+---------+---------------+
|     87 |   57 |     57 | 33008.0 | +             |
+--------+------+--------+---------+---------------+
|     87 |   57 |     57 | 33008.0 | +             |
+--------+------+--------+---------+---------------+
|     89 |   59 |     59 | 33014.0 | +             |
+--------+------+--------+---------+---------------+
|     89 |   59 |     59 | 33014.0 | +             |
+--------+------+--------+---------+---------------+
|     89 |   59 |     59 | 33014.0 | +             |
+--------+------+--------+---------+---------------+
|     92 |   62 |     62 | 33018.0 | +             |
+--------+------+--------+---------+---------------+
|     92 |   62 |     62 | 33018.0 | +             |
+--------+------+--------+---------+---------------+
|     92 |   62 |     62 | 33018.0 | +             |
+--------+------+--------+---------+---------------+
|     92 |   62 |     62 | 33018.0 | +             |
+--------+------+--------+---------+---------------+
|     92 |   62 |     62 | 33018.0 | +             |
+--------+------+--------+---------+---------------+
|     95 |   65 |     65 | 33021.0 | +             |
+--------+------+--------+---------+---------------+
|     98 |   68 |     68 | 33023.0 | +             |
+--------+------+--------+---------+---------------+
|     98 |   68 |     68 | 33023.0 | +             |
+--------+------+--------+---------+---------------+
|     98 |   68 |     68 | 33023.0 | +             |
+--------+------+--------+---------+---------------+
|     30 |    0 |      0 | -       | -             |
+--------+------+--------+---------+---------------+
|     30 |    0 |      0 | -       | -             |
+--------+------+--------+---------+---------------+
|     30 |    0 |      0 | -       | -             |
+--------+------+--------+---------+---------------+
|     30 |    0 |      0 | -       | -             |
+--------+------+--------+---------+---------------+
|     30 |    0 |      0 | -       | -             |
+--------+------+--------+---------+---------------+
|     30 |    0 |      0 | -       | -             |
+--------+------+--------+---------+---------------+
|     30 |    0 |      0 | -       | -             |
+--------+------+--------+---------+---------------+
|     30 |    0 |      0 | -       | -             |
+--------+------+--------+---------+---------------+
|     30 |    0 |      0 | -       | -             |
+--------+------+--------+---------+---------------+
|     30 |    0 |      0 | -       | -             |
+--------+------+--------+---------+---------------+
|     30 |    0 |      0 | -       | -             |
+--------+------+--------+---------+---------------+
|     30 |    0 |      0 | -       | -             |
+--------+------+--------+---------+---------------+
|     30 |    0 |      0 | -       | -             |
+--------+------+--------+---------+---------------+
|     30 |    0 |      0 | -       | -             |
+--------+------+--------+---------+---------------+
|     30 |    0 |      0 | -       | -             |
+--------+------+--------+---------+---------------+
|     30 |    0 |      0 | -       | -             |
+--------+------+--------+---------+---------------+
|     30 |    0 |      0 | -       | -             |